      DATA ATOM/
     $     'H ','He','Li','Be','B ','C ','N ','O ',
     $     'F ','Ne','Na','Mg','Al','Si','P ','S ', 
     $     'Cl','Ar','K ','Ca','Sc','Ti','V ','Cr',
     $     'Mn','Fe','Co','Ni','Cu','Zn','Ga','Ge',
     $     'As','Se','Br','Kr','Rb','Sr','Y ','Zr',
     $     'Nb','Mo','Tc','Ru','Rh','Pd','Ag','Cd',
     $     'In','Sn','Sb','Te','I ','Xe','Cs','Ba',
     $     'La','Ce','Pr','Nd','Pm','Sm','Eu','Gd',
     $     'Tb','Dy','Ho','Er','Tm','Yb','Lu','Hf',
     $     'Ta','W ','Re','Os','Ir','Pt','Au','Hg',
     $     'Tl','Pb','Bi','Po','At','Rn','Fr','Ra',
     $     'Ac','Th','Pa','U ','Np','Pu','Am','Cm',
     $     'Bk','Cf','Es','Fm'/

      DATA ATOM_UPPER/
     $     'H ','HE','LI','BE','B ','C ','N ','O ',
     $     'F ','NE','NA','MG','AL','SI','P ','S ', 
     $     'CL','AR','K ','CA','SC','TI','V ','CR',
     $     'MN','FE','CO','NI','CU','ZN','GA','GE',
     $     'AS','SE','BR','KR','RB','SR','Y ','ZR',
     $     'NB','MO','TC','RU','RH','PD','AG','CD',
     $     'IN','SN','SB','TE','I ','XE','CS','BA',
     $     'LA','CE','PR','ND','PM','SM','EU','GD',
     $     'TB','DY','HO','ER','TM','YB','LU','HF',
     $     'TA','W ','RE','OS','IR','PT','AU','HG',
     $     'TL','PB','BI','PO','AT','RN','FR','RA',
     $     'AC','TH','PA','U ','NP','PU','AM','CM',
     $     'BK','CF','ES','FM'/
